stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install  # Installera beroenden, anpassa beroende på ditt projekt
    - npm run build  # Bygg din webbplats, anpassa beroende på ditt projekt
  artifacts:
    paths:
      - public/  # Om din webbplats genererar filer i en mapp (t.ex., dist/ eller build/), ange den här

deploy:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public/
  only:
    - master  # Utlös deploy endast när du pushar till master-grenen
  script:
    - echo 'Deploy to GitLab Pages'
  environment:
    name: production
 
  dependencies:
    - build
  except:
    - schedules

# Functions that should be executed before the build script is run
before_script:
  - npm install
  - npm run dev
